artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Godwin45/datasets/raw/main/student.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

feature_engineering:
  root_dir: artifacts/data_ingestion
  student_df: artifacts/data_ingestion/data.csv

data_transformation:
  root_dir: artifacts/data_ingestion
  train_df: artifacts/data_ingestion/train.csv
  test_df: artifacts/data_ingestion/text.csv

training:
  root_dir: artifacts/data_ingestion
  train_df: artifacts/data_ingestion/train.csv
  trained_model_path: artifacts/training